# Generated by Django 4.2.7 on 2023-11-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicstyle',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='musicstyle',
            index=models.Index(fields=['name'], name='music_music_name_634be3_idx'),
        ),
    ]
