# Generated by Django 5.0 on 2023-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0002_alter_judge_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='job',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
