# Generated by Django 5.0 on 2023-12-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0005_alter_judge_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='job',
        ),
    ]
