# Generated by Django 5.0 on 2023-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0006_remove_judge_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='job',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
